name: ci

on:
  push:
    branches:
      - '8.1-cli'
      - '8.1-fpm-nginx'
      - '8.2-cli'
      - '8.2-fpm-nginx'
      - '8.3-cli'
      - '8.3-fpm-nginx'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.7.0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mbaptista11/php-base-image:${{ env.CI_ACTION_REF_NAME }}
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8